import 'package:dis_app/l10n/app_localizations.dart';
import 'package:dis_app/models/permission.dart';

/// Die Woerter fuer jede Berechtigung.
///
/// Sie standen vorher als Konstruktor-Argumente im Enum, also in derselben
/// Datei, die beschreibt, wie Berechtigungen gespeichert werden. Ein Enum
/// wird einmal gebaut und danach nie wieder; die Sprache kann sich in der
/// Zwischenzeit aendern. Deshalb stehen die Woerter hier und werden bei
/// jedem Aufruf frisch aus AppLocalizations geholt.
///
/// Diese Texte sind kein Beiwerk: Sie entscheiden, ob jemand versteht, was
/// er einem anderen Anteil gerade erlaubt oder wegnimmt.
extension PermissionText on Permission {
  String label(AppLocalizations l10n) {
    switch (this) {
      case Permission.createProfiles:
        return l10n.permCreateProfilesLabel;
      case Permission.deactivateProfiles:
        return l10n.permDeactivateProfilesLabel;
      case Permission.managePermissions:
        return l10n.permManagePermissionsLabel;
      case Permission.accessSettings:
        return l10n.permAccessSettingsLabel;
      case Permission.viewChat:
        return l10n.permViewChatLabel;
      case Permission.sendChatMessage:
        return l10n.permSendChatMessageLabel;
      case Permission.sendTextMessage:
        return l10n.permSendTextMessageLabel;
      case Permission.sendDoodle:
        return l10n.permSendDoodleLabel;
      case Permission.sendVoiceMessage:
        return l10n.permSendVoiceMessageLabel;
      case Permission.sendImage:
        return l10n.permSendImageLabel;
      case Permission.sendVideo:
        return l10n.permSendVideoLabel;
      case Permission.deleteOwnMessages:
        return l10n.permDeleteOwnMessagesLabel;
      case Permission.deleteAllMessages:
        return l10n.permDeleteAllMessagesLabel;
      case Permission.viewCalendar:
        return l10n.permViewCalendarLabel;
      case Permission.createEvents:
        return l10n.permCreateEventsLabel;
      case Permission.editOwnEvents:
        return l10n.permEditOwnEventsLabel;
      case Permission.editAllEvents:
        return l10n.permEditAllEventsLabel;
      case Permission.deleteOwnEvents:
        return l10n.permDeleteOwnEventsLabel;
      case Permission.deleteAllEvents:
        return l10n.permDeleteAllEventsLabel;
      case Permission.attachEventMedia:
        return l10n.permAttachEventMediaLabel;
      case Permission.commentOnCalendarEvents:
        return l10n.permCommentOnCalendarEventsLabel;
      case Permission.viewMedication:
        return l10n.permViewMedicationLabel;
      case Permission.manageMedication:
        return l10n.permManageMedicationLabel;
      case Permission.logMedication:
        return l10n.permLogMedicationLabel;
      case Permission.overrideMedicationLog:
        return l10n.permOverrideMedicationLogLabel;
      case Permission.commentOnMedication:
        return l10n.permCommentOnMedicationLabel;
      case Permission.viewOwnDiary:
        return l10n.permViewOwnDiaryLabel;
      case Permission.viewAllDiaries:
        return l10n.permViewAllDiariesLabel;
      case Permission.writeDiary:
        return l10n.permWriteDiaryLabel;
      case Permission.viewContacts:
        return l10n.permViewContactsLabel;
      case Permission.manageContacts:
        return l10n.permManageContactsLabel;
      case Permission.commentOnContacts:
        return l10n.permCommentOnContactsLabel;
      case Permission.viewFinder:
        return l10n.permViewFinderLabel;
      case Permission.manageFinder:
        return l10n.permManageFinderLabel;
      case Permission.commentOnFinderEntries:
        return l10n.permCommentOnFinderEntriesLabel;
      case Permission.createDiaryEntry:
        return l10n.permCreateDiaryEntryLabel;
      case Permission.editOwnDiaryEntries:
        return l10n.permEditOwnDiaryEntriesLabel;
      case Permission.editAllDiaryEntries:
        return l10n.permEditAllDiaryEntriesLabel;
      case Permission.deleteOwnDiaryEntries:
        return l10n.permDeleteOwnDiaryEntriesLabel;
      case Permission.deleteAllDiaryEntries:
        return l10n.permDeleteAllDiaryEntriesLabel;
      case Permission.commentOnDiaryEntries:
        return l10n.permCommentOnDiaryEntriesLabel;
      case Permission.viewSharedEntries:
        return l10n.permViewSharedEntriesLabel;
      case Permission.viewEmergencyContacts:
        return l10n.permViewEmergencyContactsLabel;
      case Permission.callEmergencyContacts:
        return l10n.permCallEmergencyContactsLabel;
      case Permission.editEmergencyContacts:
        return l10n.permEditEmergencyContactsLabel;
      case Permission.resetPasswords:
        return l10n.permResetPasswordsLabel;
      case Permission.changeOwnPassword:
        return l10n.permChangeOwnPasswordLabel;
      case Permission.enableBiometrics:
        return l10n.permEnableBiometricsLabel;
      case Permission.viewChatTab:
        return l10n.permViewChatTabLabel;
      case Permission.viewFeedbackTab:
        return l10n.permViewFeedbackTabLabel;
      case Permission.viewCalendarTab:
        return l10n.permViewCalendarTabLabel;
      case Permission.viewMedicationTab:
        return l10n.permViewMedicationTabLabel;
      case Permission.viewDiaryTab:
        return l10n.permViewDiaryTabLabel;
      case Permission.viewContactsTab:
        return l10n.permViewContactsTabLabel;
      case Permission.viewFinderTab:
        return l10n.permViewFinderTabLabel;
      case Permission.viewEmergencyTab:
        return l10n.permViewEmergencyTabLabel;
      case Permission.viewHelpTab:
        return l10n.permViewHelpTabLabel;
      case Permission.viewMantrasTab:
        return l10n.permViewMantrasTabLabel;
      case Permission.viewGamesTab:
        return l10n.permViewGamesTabLabel;
      case Permission.viewTimelineTab:
        return l10n.permViewTimelineTabLabel;
    }
  }

  String description(AppLocalizations l10n) {
    switch (this) {
      case Permission.createProfiles:
        return l10n.permCreateProfilesDesc;
      case Permission.deactivateProfiles:
        return l10n.permDeactivateProfilesDesc;
      case Permission.managePermissions:
        return l10n.permManagePermissionsDesc;
      case Permission.accessSettings:
        return l10n.permAccessSettingsDesc;
      case Permission.viewChat:
        return l10n.permViewChatDesc;
      case Permission.sendChatMessage:
        return l10n.permSendChatMessageDesc;
      case Permission.sendTextMessage:
        return l10n.permSendTextMessageDesc;
      case Permission.sendDoodle:
        return l10n.permSendDoodleDesc;
      case Permission.sendVoiceMessage:
        return l10n.permSendVoiceMessageDesc;
      case Permission.sendImage:
        return l10n.permSendImageDesc;
      case Permission.sendVideo:
        return l10n.permSendVideoDesc;
      case Permission.deleteOwnMessages:
        return l10n.permDeleteOwnMessagesDesc;
      case Permission.deleteAllMessages:
        return l10n.permDeleteAllMessagesDesc;
      case Permission.viewCalendar:
        return l10n.permViewCalendarDesc;
      case Permission.createEvents:
        return l10n.permCreateEventsDesc;
      case Permission.editOwnEvents:
        return l10n.permEditOwnEventsDesc;
      case Permission.editAllEvents:
        return l10n.permEditAllEventsDesc;
      case Permission.deleteOwnEvents:
        return l10n.permDeleteOwnEventsDesc;
      case Permission.deleteAllEvents:
        return l10n.permDeleteAllEventsDesc;
      case Permission.attachEventMedia:
        return l10n.permAttachEventMediaDesc;
      case Permission.commentOnCalendarEvents:
        return l10n.permCommentOnCalendarEventsDesc;
      case Permission.viewMedication:
        return l10n.permViewMedicationDesc;
      case Permission.manageMedication:
        return l10n.permManageMedicationDesc;
      case Permission.logMedication:
        return l10n.permLogMedicationDesc;
      case Permission.overrideMedicationLog:
        return l10n.permOverrideMedicationLogDesc;
      case Permission.commentOnMedication:
        return l10n.permCommentOnMedicationDesc;
      case Permission.viewOwnDiary:
        return l10n.permViewOwnDiaryDesc;
      case Permission.viewAllDiaries:
        return l10n.permViewAllDiariesDesc;
      case Permission.writeDiary:
        return l10n.permWriteDiaryDesc;
      case Permission.viewContacts:
        return l10n.permViewContactsDesc;
      case Permission.manageContacts:
        return l10n.permManageContactsDesc;
      case Permission.commentOnContacts:
        return l10n.permCommentOnContactsDesc;
      case Permission.viewFinder:
        return l10n.permViewFinderDesc;
      case Permission.manageFinder:
        return l10n.permManageFinderDesc;
      case Permission.commentOnFinderEntries:
        return l10n.permCommentOnFinderEntriesDesc;
      case Permission.createDiaryEntry:
        return l10n.permCreateDiaryEntryDesc;
      case Permission.editOwnDiaryEntries:
        return l10n.permEditOwnDiaryEntriesDesc;
      case Permission.editAllDiaryEntries:
        return l10n.permEditAllDiaryEntriesDesc;
      case Permission.deleteOwnDiaryEntries:
        return l10n.permDeleteOwnDiaryEntriesDesc;
      case Permission.deleteAllDiaryEntries:
        return l10n.permDeleteAllDiaryEntriesDesc;
      case Permission.commentOnDiaryEntries:
        return l10n.permCommentOnDiaryEntriesDesc;
      case Permission.viewSharedEntries:
        return l10n.permViewSharedEntriesDesc;
      case Permission.viewEmergencyContacts:
        return l10n.permViewEmergencyContactsDesc;
      case Permission.callEmergencyContacts:
        return l10n.permCallEmergencyContactsDesc;
      case Permission.editEmergencyContacts:
        return l10n.permEditEmergencyContactsDesc;
      case Permission.resetPasswords:
        return l10n.permResetPasswordsDesc;
      case Permission.changeOwnPassword:
        return l10n.permChangeOwnPasswordDesc;
      case Permission.enableBiometrics:
        return l10n.permEnableBiometricsDesc;
      case Permission.viewChatTab:
        return l10n.permViewChatTabDesc;
      case Permission.viewFeedbackTab:
        return l10n.permViewFeedbackTabDesc;
      case Permission.viewCalendarTab:
        return l10n.permViewCalendarTabDesc;
      case Permission.viewMedicationTab:
        return l10n.permViewMedicationTabDesc;
      case Permission.viewDiaryTab:
        return l10n.permViewDiaryTabDesc;
      case Permission.viewContactsTab:
        return l10n.permViewContactsTabDesc;
      case Permission.viewFinderTab:
        return l10n.permViewFinderTabDesc;
      case Permission.viewEmergencyTab:
        return l10n.permViewEmergencyTabDesc;
      case Permission.viewHelpTab:
        return l10n.permViewHelpTabDesc;
      case Permission.viewMantrasTab:
        return l10n.permViewMantrasTabDesc;
      case Permission.viewGamesTab:
        return l10n.permViewGamesTabDesc;
      case Permission.viewTimelineTab:
        return l10n.permViewTimelineTabDesc;
    }
  }
}
