// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:dis_app/models/calendar_event.dart';
import 'package:dis_app/models/chat_message.dart';
import 'package:dis_app/models/comment.dart';
import 'package:dis_app/models/contact.dart';
import 'package:dis_app/models/contact_comment.dart';
import 'package:dis_app/models/contact_rating.dart';
import 'package:dis_app/models/diary_comment.dart';
import 'package:dis_app/models/diary_entry.dart';
import 'package:dis_app/models/finder_item.dart';
import 'package:dis_app/models/location_history_entry.dart';
import 'package:dis_app/models/medication.dart';
import 'package:dis_app/models/notification_queue_entry.dart';
import 'package:dis_app/models/pending_telemetry_event.dart';
import 'package:dis_app/models/profile.dart';
import 'package:dis_app/models/profile_switch_event.dart';
import 'package:dis_app/models/puzzle_config.dart';
import 'package:dis_app/models/transmission_log_entry.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CalendarEventAdapter());
    registerAdapter(ChatMessageAdapter());
    registerAdapter(CommentAdapter());
    registerAdapter(CommentableTypeAdapter());
    registerAdapter(ContactAdapter());
    registerAdapter(ContactCategoryAdapter());
    registerAdapter(ContactCommentAdapter());
    registerAdapter(ContactRatingAdapter());
    registerAdapter(DiaryCommentAdapter());
    registerAdapter(DiaryEntryAdapter());
    registerAdapter(EntryMoodAdapter());
    registerAdapter(EntryPriorityAdapter());
    registerAdapter(FinderItemAdapter());
    registerAdapter(FinderItemTypeAdapter());
    registerAdapter(LocationHistoryEntryAdapter());
    registerAdapter(MedicationAdapter());
    registerAdapter(MedicationLogAdapter());
    registerAdapter(MedicationStatusAdapter());
    registerAdapter(MedicationTypeAdapter());
    registerAdapter(MessageTypeAdapter());
    registerAdapter(NotificationQueueEntryAdapter());
    registerAdapter(PendingTelemetryEventAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(ProfileSwitchEventAdapter());
    registerAdapter(PuzzleConfigAdapter());
    registerAdapter(PuzzleDifficultyAdapter());
    registerAdapter(PuzzleImageSourceAdapter());
    registerAdapter(PuzzleTypeAdapter());
    registerAdapter(TransmissionChannelAdapter());
    registerAdapter(TransmissionLogEntryAdapter());
    registerAdapter(TransmissionStatusAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CalendarEventAdapter());
    registerAdapter(ChatMessageAdapter());
    registerAdapter(CommentAdapter());
    registerAdapter(CommentableTypeAdapter());
    registerAdapter(ContactAdapter());
    registerAdapter(ContactCategoryAdapter());
    registerAdapter(ContactCommentAdapter());
    registerAdapter(ContactRatingAdapter());
    registerAdapter(DiaryCommentAdapter());
    registerAdapter(DiaryEntryAdapter());
    registerAdapter(EntryMoodAdapter());
    registerAdapter(EntryPriorityAdapter());
    registerAdapter(FinderItemAdapter());
    registerAdapter(FinderItemTypeAdapter());
    registerAdapter(LocationHistoryEntryAdapter());
    registerAdapter(MedicationAdapter());
    registerAdapter(MedicationLogAdapter());
    registerAdapter(MedicationStatusAdapter());
    registerAdapter(MedicationTypeAdapter());
    registerAdapter(MessageTypeAdapter());
    registerAdapter(NotificationQueueEntryAdapter());
    registerAdapter(PendingTelemetryEventAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(ProfileSwitchEventAdapter());
    registerAdapter(PuzzleConfigAdapter());
    registerAdapter(PuzzleDifficultyAdapter());
    registerAdapter(PuzzleImageSourceAdapter());
    registerAdapter(PuzzleTypeAdapter());
    registerAdapter(TransmissionChannelAdapter());
    registerAdapter(TransmissionLogEntryAdapter());
    registerAdapter(TransmissionStatusAdapter());
  }
}
